// <auto-generated />
using System;
using Friggy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Friggy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FriggyDbContext))]
    [Migration("20260806111514_AddCatalogs")]
    partial class AddCatalogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Friggy.Domain.Catalogs.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.MealType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.ToTable("meal_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_meal_types_order_non_negative", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.RecipeTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("recipe_tags", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.UnitType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("unit_types", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.Ingredient", b =>
                {
                    b.OwnsOne("Friggy.Domain.Catalogs.CatalogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("IngredientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("IngredientId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.MealType", b =>
                {
                    b.OwnsOne("Friggy.Domain.Catalogs.CatalogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("MealTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("MealTypeId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("meal_types");

                            b1.WithOwner()
                                .HasForeignKey("MealTypeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.RecipeTag", b =>
                {
                    b.OwnsOne("Friggy.Domain.Catalogs.CatalogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("RecipeTagId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("RecipeTagId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("recipe_tags");

                            b1.WithOwner()
                                .HasForeignKey("RecipeTagId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.UnitType", b =>
                {
                    b.OwnsOne("Friggy.Domain.Catalogs.CatalogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("UnitTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("UnitTypeId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("unit_types");

                            b1.WithOwner()
                                .HasForeignKey("UnitTypeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
