// <auto-generated />
using System;
using Friggy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Friggy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FriggyDbContext))]
    [Migration("20260822081846_AddDailyPlanTemplates")]
    partial class AddDailyPlanTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Friggy.Domain.Catalogs.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.MealType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.ToTable("meal_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_meal_types_order_non_negative", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.RecipeTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("recipe_tags", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.UnitType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("unit_types", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlanTemplates.DailyPlanTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("daily_plan_templates", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlanTemplates.DailyPlanTemplateMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyPlanTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_plan_template_id");

                    b.Property<Guid>("MealTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_type_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<TimeOnly?>("PlannedTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("planned_time");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.HasKey("Id");

                    b.HasAlternateKey("DailyPlanTemplateId", "MealTypeId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("DailyPlanTemplateId", "Order")
                        .IsUnique();

                    b.ToTable("daily_plan_template_meals", null, t =>
                        {
                            t.HasCheckConstraint("ck_daily_plan_template_meals_order_non_negative", "\"order\" >= 0");

                            t.HasCheckConstraint("ck_daily_plan_template_meals_servings_positive", "servings > 0");
                        });
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlans.DailyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("daily_plans", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlans.MealPlanEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AlternativeDescription")
                        .HasColumnType("text")
                        .HasColumnName("alternative_description");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("DailyPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_plan_id");

                    b.Property<Guid>("MealTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_type_id");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("servings");

                    b.Property<string>("SkippedReason")
                        .HasColumnType("text")
                        .HasColumnName("skipped_reason");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("DailyPlanId", "MealTypeId")
                        .IsUnique();

                    b.ToTable("meal_plan_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_meal_plan_entries_completion_state", "(status = 1 AND completed_at IS NOT NULL) OR (status <> 1 AND completed_at IS NULL)");

                            t.HasCheckConstraint("ck_meal_plan_entries_servings_positive", "servings > 0");

                            t.HasCheckConstraint("ck_meal_plan_entries_skipped_state", "(status = 2 AND skipped_reason IS NOT NULL AND btrim(skipped_reason) <> '') OR (status <> 2 AND skipped_reason IS NULL AND alternative_description IS NULL)");

                            t.HasCheckConstraint("ck_meal_plan_entries_status_valid", "status IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlans.MealPlanSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_plan_id");

                    b.Property<Guid>("MealTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_type_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<TimeOnly?>("PlannedTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("planned_time");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("DailyPlanId", "Order")
                        .IsUnique();

                    b.ToTable("meal_plan_slots", null, t =>
                        {
                            t.HasCheckConstraint("ck_meal_plan_slots_order_non_negative", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("Friggy.Domain.Inventory.InventoryLot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("UnitTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_type_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("IngredientId", "UnitTypeId", "ExpirationDate");

                    b.ToTable("inventory_lots", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_lots_quantity_non_negative", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("Friggy.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Delta")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("delta");

                    b.Property<Guid>("InventoryLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_lot_id");

                    b.Property<Guid?>("MealPlanEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_plan_entry_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal>("ResultingQuantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("resulting_quantity");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanEntryId");

                    b.HasIndex("InventoryLotId", "OccurredAt");

                    b.ToTable("inventory_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_movements_delta_non_zero", "delta <> 0");

                            t.HasCheckConstraint("ck_inventory_movements_result_non_negative", "resulting_quantity >= 0");
                        });
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("EstimatedTime")
                        .HasColumnType("interval")
                        .HasColumnName("estimated_time");

                    b.HasKey("Id");

                    b.ToTable("recipes", null, t =>
                        {
                            t.HasCheckConstraint("ck_recipes_estimated_time_non_negative", "estimated_time >= interval '0 minutes'");
                        });
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("UnitTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_type_id");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("recipe_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("ck_recipe_ingredients_order_non_negative", "\"order\" >= 0");

                            t.HasCheckConstraint("ck_recipe_ingredients_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeMealTypeLink", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("MealTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_type_id");

                    b.HasKey("RecipeId", "MealTypeId");

                    b.HasIndex("MealTypeId");

                    b.ToTable("recipe_meal_types", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<TimeSpan?>("EstimatedTime")
                        .HasColumnType("interval")
                        .HasColumnName("estimated_time");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Order")
                        .IsUnique();

                    b.ToTable("recipe_steps", null, t =>
                        {
                            t.HasCheckConstraint("ck_recipe_steps_estimated_time_non_negative", "estimated_time IS NULL OR estimated_time >= interval '0 minutes'");

                            t.HasCheckConstraint("ck_recipe_steps_order_non_negative", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeStepIngredientLink", b =>
                {
                    b.Property<Guid>("RecipeStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_step_id");

                    b.Property<Guid>("RecipeIngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_ingredient_id");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("RecipeStepId", "RecipeIngredientId");

                    b.HasIndex("RecipeId", "RecipeIngredientId");

                    b.HasIndex("RecipeId", "RecipeStepId");

                    b.ToTable("recipe_step_ingredients", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeTagLink", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("RecipeTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_tag_id");

                    b.HasKey("RecipeId", "RecipeTagId");

                    b.HasIndex("RecipeTagId");

                    b.ToTable("recipe_recipe_tags", (string)null);
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.Ingredient", b =>
                {
                    b.OwnsOne("Friggy.Domain.Catalogs.CatalogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("IngredientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("IngredientId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.MealType", b =>
                {
                    b.OwnsOne("Friggy.Domain.Catalogs.CatalogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("MealTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("MealTypeId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("meal_types");

                            b1.WithOwner()
                                .HasForeignKey("MealTypeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.RecipeTag", b =>
                {
                    b.OwnsOne("Friggy.Domain.Catalogs.CatalogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("RecipeTagId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("RecipeTagId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("recipe_tags");

                            b1.WithOwner()
                                .HasForeignKey("RecipeTagId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Catalogs.UnitType", b =>
                {
                    b.OwnsOne("Friggy.Domain.Catalogs.CatalogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("UnitTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("UnitTypeId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("unit_types");

                            b1.WithOwner()
                                .HasForeignKey("UnitTypeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlanTemplates.DailyPlanTemplate", b =>
                {
                    b.OwnsOne("Friggy.Domain.Catalogs.CatalogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("DailyPlanTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("DailyPlanTemplateId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("daily_plan_templates");

                            b1.WithOwner()
                                .HasForeignKey("DailyPlanTemplateId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlanTemplates.DailyPlanTemplateMeal", b =>
                {
                    b.HasOne("Friggy.Domain.DailyPlanTemplates.DailyPlanTemplate", null)
                        .WithMany("Meals")
                        .HasForeignKey("DailyPlanTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Catalogs.MealType", null)
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlans.MealPlanEntry", b =>
                {
                    b.HasOne("Friggy.Domain.DailyPlans.DailyPlan", null)
                        .WithMany("Entries")
                        .HasForeignKey("DailyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Catalogs.MealType", null)
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.DailyPlans.MealPlanSlot", null)
                        .WithOne()
                        .HasForeignKey("Friggy.Domain.DailyPlans.MealPlanEntry", "DailyPlanId", "MealTypeId")
                        .HasPrincipalKey("Friggy.Domain.DailyPlans.MealPlanSlot", "DailyPlanId", "MealTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_meal_plan_entries_meal_plan_slots");
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlans.MealPlanSlot", b =>
                {
                    b.HasOne("Friggy.Domain.DailyPlans.DailyPlan", null)
                        .WithMany("Slots")
                        .HasForeignKey("DailyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Catalogs.MealType", null)
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Inventory.InventoryLot", b =>
                {
                    b.HasOne("Friggy.Domain.Catalogs.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Catalogs.UnitType", null)
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Inventory.InventoryMovement", b =>
                {
                    b.HasOne("Friggy.Domain.Inventory.InventoryLot", null)
                        .WithMany("Movements")
                        .HasForeignKey("InventoryLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.DailyPlans.MealPlanEntry", null)
                        .WithMany()
                        .HasForeignKey("MealPlanEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.Recipe", b =>
                {
                    b.OwnsOne("Friggy.Domain.Catalogs.CatalogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("RecipeId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("Friggy.Domain.Catalogs.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Recipes.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Catalogs.UnitType", null)
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeMealTypeLink", b =>
                {
                    b.HasOne("Friggy.Domain.Catalogs.MealType", null)
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Recipes.Recipe", null)
                        .WithMany("MealTypes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeStep", b =>
                {
                    b.HasOne("Friggy.Domain.Recipes.Recipe", null)
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeStepIngredientLink", b =>
                {
                    b.HasOne("Friggy.Domain.Recipes.RecipeIngredient", null)
                        .WithMany()
                        .HasForeignKey("RecipeId", "RecipeIngredientId")
                        .HasPrincipalKey("RecipeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Recipes.RecipeStep", null)
                        .WithMany("IngredientLinks")
                        .HasForeignKey("RecipeId", "RecipeStepId")
                        .HasPrincipalKey("RecipeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeTagLink", b =>
                {
                    b.HasOne("Friggy.Domain.Recipes.Recipe", null)
                        .WithMany("Tags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friggy.Domain.Catalogs.RecipeTag", null)
                        .WithMany()
                        .HasForeignKey("RecipeTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlanTemplates.DailyPlanTemplate", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("Friggy.Domain.DailyPlans.DailyPlan", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Friggy.Domain.Inventory.InventoryLot", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("MealTypes");

                    b.Navigation("Steps");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Friggy.Domain.Recipes.RecipeStep", b =>
                {
                    b.Navigation("IngredientLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
